name: Sample Orca IaC Scan Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  orca-iac_scan:
    name: Orca IaC Scan
    runs-on: ubuntu-latest
    env:
      PROJECT_KEY: slrk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Debug workspace
        run: |
          echo "Current branch/ref:"
          git log --oneline -3
          echo ""
          echo "Files in workspace:"
          find . -not -path './.git/*' -type f
          echo "=== git log ==="
          git log --oneline -3
          echo "=== s3.tf contents ==="
          cat aws/s3.tf
    
      - name: Run Orca IaC Scan
        uses: orcasecurity/shiftleft-iac-action@v1
        id: orca_scan
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          path: "./aws"
          show_annotations: true

      - name: Orca IaC Scan - Binary
        run: |
          echo "Installing Orca-cli binary..."
          set +e
          apt update && apt install -y curl
          curl -sfL 'https://raw.GitHubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash
          orca-cli -p "${PROJECT_KEY}" iac scan .
          
