name: Sample Orca IaC Scan Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  orca-iac_scan:
    name: Orca IaC Scan
    runs-on: ubuntu-latest
    env:
      PROJECT_KEY: slrk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        #with:
          #ref: ${{ github.head_ref }} # checkout source branch of PR
          #ref: ${{ github.base_ref }}  # Target branch of PR
          # ref: ${{ github.event.pull_request.head.ref }}
          # ref: refs/heads/main
          #fetch-depth: 0

      - name: Git Status
        run: | 
          git status
          ls -la ./aws/


      - name: Run Orca IaC Scan
        uses: orcasecurity/shiftleft-iac-action@v1
        id: orca_scan
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          path: "."
          show_annotations: true

      - name: Orca IaC Scan - Binary
        env:
          ORCA_SECURITY_API_TOKEN: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
        run: |
          echo "Installing Orca-cli binary..."
          set +e
          apt update && apt install -y curl
          curl -sfL 'https://raw.GitHubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash
          orca-cli -p "${PROJECT_KEY}" iac scan ${{ github.workspace }}
          
 
